#!/bin/bash
#
# HAMAYNI Contract: demo-22c462aa-fc9d-494d-8ad4-27461096352a
# Template: hamayni.nginx.standalone v1.0.0
# Generated: 2026-02-01T15:41:30.539Z
# Integrity Hash: 01f7451ffa6bdd8b0cd61c9089ae6fe0347aad02afbfedaae15a121794604a85
#
# DO NOT MODIFY - Auto-generated by HAMAYNI Factory
#

set -euo pipefail
IFS=$'\n\t'

# ============================================
# LOGGING FUNCTIONS
# ============================================

LOG_FILE="/var/log/hamayni/${CONTRACT_ID:-unknown}.log"
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true

log_msg() {
  local level="$1" tag="$2" msg="$3"
  local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  local log_line="[$timestamp] [$level] [$tag] $msg"
  echo "$log_line"
  echo "$log_line" >> "$LOG_FILE" 2>/dev/null || true
}

log_gate() { log_msg "GATE" "$1" "$2"; }
log_op() { log_msg "OP" "$1" "$2"; }
log_error() { log_msg "ERROR" "$1" "$2"; }
log_warn() { log_msg "WARN" "$1" "$2"; }
log_info() { log_msg "INFO" "$1" "$2"; }

# ============================================
# CONTRACT METADATA
# ============================================

export CONTRACT_ID="demo-22c462aa-fc9d-494d-8ad4-27461096352a"
export TEMPLATE_SLUG="hamayni.nginx.standalone"
export TEMPLATE_VERSION="1.0.0"
export HFC_VERSION="1.0"
export INTEGRITY_HASH="01f7451ffa6bdd8b0cd61c9089ae6fe0347aad02afbfedaae15a121794604a85"

log_info "INIT" "Starting HAMAYNI contract execution"
log_info "INIT" "Contract ID: $CONTRACT_ID"

# ============================================
# GATES - Pre-execution checks
# ============================================

# [GATE] check-os: Verify Ubuntu/Debian OS
log_gate "check-os" "Checking: Verify Ubuntu/Debian OS"
if ! (command -v apt-get); then
  log_error "GATE_FAILED" "This contract requires Ubuntu/Debian (apt-get not found)"
  exit 1
fi

# [GATE] check-port-80: Verify port 80 is free
log_gate "check-port-80" "Checking: Verify port 80 is free"
if ! (! netstat -tuln 2>/dev/null | grep -q ":80 " && ! ss -tuln 2>/dev/null | grep -q ":80 "); then
  log_warn "GATE_WARNING" "Port 80 is already in use - Nginx may fail to start"
fi

# ============================================
# BOM - Bill of Materials deployment
# ============================================

# [BOM] nginx-config: Nginx site configuration
log_op "BOM" "Deploying file /etc/nginx/sites-available/example.com"
mkdir -p "$(dirname "/etc/nginx/sites-available/example.com")"
echo "c2VydmVyIHsKICAgIGxpc3RlbiA4MDsKICAgIHNlcnZlcl9uYW1lIGV4YW1wbGUuY29tIHd3dy5leGFtcGxlLmNvbTsKCiAgICByb290IC92YXIvd3d3L2V4YW1wbGUuY29tOwogICAgaW5kZXggaW5kZXguaHRtbCBpbmRleC5odG07CgogICAgbG9jYXRpb24gLyB7CiAgICAgICAgdHJ5X2ZpbGVzICR1cmkgJHVyaS8gPTQwNDsKICAgIH0KCiAgICBhY2Nlc3NfbG9nIC92YXIvbG9nL25naW54L2V4YW1wbGUuY29tX2FjY2Vzcy5sb2c7CiAgICBlcnJvcl9sb2cgL3Zhci9sb2cvbmdpbngvZXhhbXBsZS5jb21fZXJyb3IubG9nOwp9" | base64 -d > "/etc/nginx/sites-available/example.com"
chmod 0644 "/etc/nginx/sites-available/example.com"
chown root:root "/etc/nginx/sites-available/example.com"
log_op "BOM" "Deployed /etc/nginx/sites-available/example.com successfully"

# [BOM] dir-webroot: Web root directory
log_op "BOM" "Creating directory /var/www/example.com"
mkdir -p "/var/www/example.com"
chmod 0755 "/var/www/example.com"
chown www-data:www-data "/var/www/example.com"
log_op "BOM" "Created directory /var/www/example.com successfully"

# [BOM] index-html: Default homepage
log_op "BOM" "Deploying file /var/www/example.com/index.html"
mkdir -p "$(dirname "/var/www/example.com/index.html")"
echo "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPGhlYWQ+CiAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+CiAgICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMCI+CiAgICA8dGl0bGU+V2VsY29tZSB0byBleGFtcGxlLmNvbTwvdGl0bGU+CjwvaGVhZD4KPGJvZHk+CiAgICA8aDE+SEFNQVlOSSBJbmZyYXN0cnVjdHVyZSAtIGV4YW1wbGUuY29tPC9oMT4KICAgIDxwPlRoaXMgc2l0ZSBpcyBwb3dlcmVkIGJ5IEhBTUFZTkkgQ29udHJhY3QgRW5naW5lIHYzLjE8L3A+CjwvYm9keT4KPC9odG1sPg==" | base64 -d > "/var/www/example.com/index.html"
chmod 0644 "/var/www/example.com/index.html"
chown www-data:www-data "/var/www/example.com/index.html"
log_op "BOM" "Deployed /var/www/example.com/index.html successfully"

# ============================================
# OPERATIONS - Command execution
# ============================================

# [OP:1] update-apt: Update package lists
log_op "update-apt" "Starting: Update package lists"
RETRY_COUNT=0
MAX_RETRIES=2
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  if timeout 300 bash -c 'apt-get update -qq'; then break; fi
  RETRY_COUNT=$((RETRY_COUNT + 1))
  if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
    log_warn "update-apt" "Retry $RETRY_COUNT/$MAX_RETRIES in 10s..."
    sleep 10
  else
    log_error "update-apt" "Operation failed after retries"
    exit 1
  fi
done
log_op "update-apt" "Completed successfully"

# [OP:2] install-nginx: Install Nginx web server
log_op "install-nginx" "Starting: Install Nginx web server"
RETRY_COUNT=0
MAX_RETRIES=2
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  if timeout 600 bash -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx'; then break; fi
  RETRY_COUNT=$((RETRY_COUNT + 1))
  if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
    log_warn "install-nginx" "Retry $RETRY_COUNT/$MAX_RETRIES in 10s..."
    sleep 10
  else
    log_error "install-nginx" "Operation failed after retries"
    exit 1
  fi
done
log_op "install-nginx" "Completed successfully"

# [OP:3] enable-site: Enable Nginx site configuration
log_op "enable-site" "Starting: Enable Nginx site configuration"
ln -sf /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/example.com
log_op "enable-site" "Completed successfully"

# [OP:4] test-config: Test Nginx configuration
log_op "test-config" "Starting: Test Nginx configuration"
nginx -t
log_op "test-config" "Completed successfully"

# [OP:5] reload-nginx: Reload Nginx service
log_op "reload-nginx" "Starting: Reload Nginx service"
systemctl reload nginx || systemctl restart nginx
log_op "reload-nginx" "Nginx reloaded successfully"

# [OP:6] enable-nginx: Enable Nginx on boot
log_op "enable-nginx" "Starting: Enable Nginx on boot"
systemctl enable nginx
log_op "enable-nginx" "Nginx enabled on boot"

# ============================================
# COMPLETION
# ============================================

log_info "COMPLETE" "Contract execution finished successfully"
log_info "COMPLETE" "Integrity verified: $INTEGRITY_HASH"

exit 0
